"""
Shared utility functions.
"""
from src.shared.utils.file_helpers import (
    ensure_directory,
    safe_filename,
    get_file_extension,
    get_mime_type,
    read_file,
    write_file,
    delete_file,
    copy_file,
    move_file,
    get_file_size,
    list_files,
    create_temp_file,
    cleanup_temp_files,
)
from src.shared.utils.string_utils import (
    slugify,
    truncate,
    mask_email,
    mask_string,
    generate_random_string,
    generate_id,
    camel_to_snake,
    snake_to_camel,
    parse_boolean,
    safe_json_loads,
    safe_json_dumps,
)
from src.shared.utils.datetime_utils import (
    utc_now,
    format_iso,
    parse_iso,
    add_days,
    add_hours,
    add_minutes,
    start_of_day,
    end_of_day,
    start_of_week,
    end_of_week,
    start_of_month,
    end_of_month,
    time_ago,
    is_expired,
)
from src.shared.utils.validation_utils import (
    is_valid_email,
    is_valid_url,
    is_valid_uuid,
    is_valid_username,
    is_valid_json,
    sanitize_html,
    validate_password_strength,
)

__all__ = [
    # File helpers
    "ensure_directory",
    "safe_filename",
    "get_file_extension",
    "get_mime_type",
    "read_file",
    "write_file",
    "delete_file",
    "copy_file",
    "move_file",
    "get_file_size",
    "list_files",
    "create_temp_file",
    "cleanup_temp_files",
    # String utils
    "slugify",
    "truncate",
    "mask_email",
    "mask_string",
    "generate_random_string",
    "generate_id",
    "camel_to_snake",
    "snake_to_camel",
    "parse_boolean",
    "safe_json_loads",
    "safe_json_dumps",
    # Datetime utils
    "utc_now",
    "format_iso",
    "parse_iso",
    "add_days",
    "add_hours",
    "add_minutes",
    "start_of_day",
    "end_of_day",
    "start_of_week",
    "end_of_week",
    "start_of_month",
    "end_of_month",
    "time_ago",
    "is_expired",
    # Validation utils
    "is_valid_email",
    "is_valid_url",
    "is_valid_uuid",
    "is_valid_username",
    "is_valid_json",
    "sanitize_html",
    "validate_password_strength",
]